### ISSUE TITLE
How to migrate Northwind.sql into mongoDB ?

### ISSUE THREAD

**Issue by MalikOvaiz** [bbraithwaite/NorthwindNode#1]

**Comment by bbraithwaite** [comment]
I have migrations for categories and products. You can find them here: https://github.com/bbraithwaite/NorthwindNode/tree/master/migrations

Also see the note on the README under heading "Populating Test Data".

**Comment by ku-santosh** [comment]
Hi,

I have some problem on running application and try my best to resolve the issue but cant make it so need your help kindly do ASAP issue is mention below also sending screenshot  :--

Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.12/$injector/modulerr?p0=northwindnode&p1=E…dflare.com%2Fajax%2Flibs%2Fangular.js%2F1.3.12%2Fangular.min.js%3A17%3A381)

![screenshot from](https://cloud.githubusercontent.com/assets/8447729/11862862/362277a8-a4b5-11e5-8a49-359bbf51da13.png)
